name: asianbitcoins
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  flutter_staggered_grid_view: ^0.3.0
  circular_check_box: ^1.0.1
  url_launcher: ^5.4.1
  image_picker: ^0.6.3+1
  percent_indicator: ^2.1.1+1
  qr_flutter: ^3.2.0
  rflutter_alert: ^1.0.3
  barcode_scan: ^1.0.0
  flutter_qr_reader: ^1.0.3
  pull_to_refresh: ^1.5.7
  badges: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: OpenSansBold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf

    - family: OpenSansLight
      fonts:
        - asset: fonts/OpenSans-Light.ttf

    - family: OpenSansRegular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family:  AnzarIcon
      fonts:
        - asset: fonts/AnzarIcon.ttf


