class PhoneCode {
  const PhoneCode({this.code, this.name});
  final String code;
  final String name;
}

List<PhoneCode> phoneCodeList = <PhoneCode>[
  const PhoneCode(code: '+93	', name: '	Afghanistan'),
  const PhoneCode(code: '+355	', name: '	Albania'),
  const PhoneCode(code: '+213	', name: '	Algeria'),
  const PhoneCode(code: '+1-684	', name: '	American Samoa'),
  const PhoneCode(code: '+376	', name: '	Andorra'),
  const PhoneCode(code: '+244	', name: '	Angola'),
  const PhoneCode(code: '+1-264	', name: '	Anguilla'),
  const PhoneCode(code: '+672	', name: '	Antarctica'),
  const PhoneCode(code: '+1-268	', name: '	Antigua '),
  const PhoneCode(code: '+54	', name: '	Argentina'),
  const PhoneCode(code: '+374	', name: '	Armenia'),
  const PhoneCode(code: '+297	', name: '	Aruba'),
  const PhoneCode(code: '+61	', name: '	Australia'),
  const PhoneCode(code: '+43	', name: '	Austria'),
  const PhoneCode(code: '+994	', name: '	Azerbaijan'),
  const PhoneCode(code: '+1-242	', name: '	Bahamas'),
  const PhoneCode(code: '+973	', name: '	Bahrain'),
  const PhoneCode(code: '+880	', name: '	Bangladesh'),
  const PhoneCode(code: '+1-246	', name: '	Barbados'),
  const PhoneCode(code: '+375	', name: '	Belarus'),
  const PhoneCode(code: '+32	', name: '	Belgium'),
  const PhoneCode(code: '+501	', name: '	Belize'),
  const PhoneCode(code: '+229	', name: '	Benin'),
  const PhoneCode(code: '+1-441	', name: '	Bermuda'),
  const PhoneCode(code: '+975	', name: '	Bhutan'),
  const PhoneCode(code: '+591	', name: '	Bolivia'),
  const PhoneCode(code: '+387	', name: '	Bosnia and Herzegovina'),
  const PhoneCode(code: '+267	', name: '	Botswana'),
  const PhoneCode(code: '+55	', name: '	Brazil'),
  const PhoneCode(code: '+246	', name: '	British Indian Ocean Territory'),
  const PhoneCode(code: '+1-284	', name: '	British Virgin Islands'),
  const PhoneCode(code: '+673	', name: '	Brunei'),
  const PhoneCode(code: '+359	', name: '	Bulgaria'),
  const PhoneCode(code: '+226	', name: '	Burkina Faso'),
  const PhoneCode(code: '+257	', name: '	Burundi'),
  const PhoneCode(code: '+855	', name: '	Cambodia'),
  const PhoneCode(code: '+237	', name: '	Cameroon'),
  const PhoneCode(code: '+1	', name: '	Canada'),
  const PhoneCode(code: '+238	', name: '	Cape Verde'),
  const PhoneCode(code: '+1-345	', name: '	Cayman Islands'),
  const PhoneCode(code: '+236	', name: '	Central African Republic'),
  const PhoneCode(code: '+235	', name: '	Chad'),
  const PhoneCode(code: '+56	', name: '	Chile'),
  const PhoneCode(code: '+86	', name: '	China'),
  const PhoneCode(code: '+61	', name: '	Christmas Island'),
  const PhoneCode(code: '+61	', name: '	Cocos Islands'),
  const PhoneCode(code: '+57	', name: '	Colombia'),
  const PhoneCode(code: '+269	', name: '	Comoros'),
  const PhoneCode(code: '+682	', name: '	Cook Islands'),
  const PhoneCode(code: '+506	', name: '	Costa Rica'),
  const PhoneCode(code: '+385	', name: '	Croatia'),
  const PhoneCode(code: '+53	', name: '	Cuba'),
  const PhoneCode(code: '+599	', name: '	Curacao'),
  const PhoneCode(code: '+357	', name: '	Cyprus'),
  const PhoneCode(code: '+420	', name: '	Czech Republic'),
  const PhoneCode(code: '+243	', name: '	Democratic Republic of the Congo'),
  const PhoneCode(code: '+45	', name: '	Denmark'),
  const PhoneCode(code: '+253	', name: '	Djibouti'),
  const PhoneCode(code: '+1-767	', name: '	Dominica'),
  const PhoneCode(code: '+1-809', name: '	Dominican Republic'),
  const PhoneCode(code: '+670	', name: '	East Timor'),
  const PhoneCode(code: '+593	', name: '	Ecuador'),
  const PhoneCode(code: '+20	', name: '	Egypt'),
  const PhoneCode(code: '+503	', name: '	El Salvador'),
  const PhoneCode(code: '+240	', name: '	Equatorial Guinea'),
  const PhoneCode(code: '+291	', name: '	Eritrea'),
  const PhoneCode(code: '+372	', name: '	Estonia'),
  const PhoneCode(code: '+251	', name: '	Ethiopia'),
  const PhoneCode(code: '+500	', name: '	Falkland Islands'),
  const PhoneCode(code: '+298	', name: '	Faroe Islands'),
  const PhoneCode(code: '+679	', name: '	Fiji'),
  const PhoneCode(code: '+358	', name: '	Finland'),
  const PhoneCode(code: '+33	', name: '	France'),
  const PhoneCode(code: '+689	', name: '	French Polynesia'),
  const PhoneCode(code: '+241	', name: '	Gabon'),
  const PhoneCode(code: '+220	', name: '	Gambia'),
  const PhoneCode(code: '+995	', name: '	Georgia'),
  const PhoneCode(code: '+49	', name: '	Germany'),
  const PhoneCode(code: '+233	', name: '	Ghana'),
  const PhoneCode(code: '+350	', name: '	Gibraltar'),
  const PhoneCode(code: '+30	', name: '	Greece'),
  const PhoneCode(code: '+299	', name: '	Greenland'),
  const PhoneCode(code: '+1-473	', name: '	Grenada'),
  const PhoneCode(code: '+1-671	', name: '	Guam'),
  const PhoneCode(code: '+502	', name: '	Guatemala'),
  const PhoneCode(code: '+44-1481	', name: '	Guernsey'),
  const PhoneCode(code: '+224	', name: '	Guinea'),
  const PhoneCode(code: '+245	', name: '	Guinea-Bissau'),
  const PhoneCode(code: '+592	', name: '	Guyana'),
  const PhoneCode(code: '+509	', name: '	Haiti'),
  const PhoneCode(code: '+504	', name: '	Honduras'),
  const PhoneCode(code: '+852	', name: '	Hong Kong'),
  const PhoneCode(code: '+36	', name: '	Hungary'),
  const PhoneCode(code: '+354	', name: '	Iceland'),
  const PhoneCode(code: '+91	', name: '	India'),
  const PhoneCode(code: '+62	', name: '	Indonesia'),
  const PhoneCode(code: '+98	', name: '	Iran'),
  const PhoneCode(code: '+964	', name: '	Iraq'),
  const PhoneCode(code: '+353	', name: '	Ireland'),
  const PhoneCode(code: '+44-1624	', name: '	Isle of Man'),
  const PhoneCode(code: '+972	', name: '	Israel'),
  const PhoneCode(code: '+39	', name: '	Italy'),
  const PhoneCode(code: '+225	', name: '	Ivory Coast'),
  const PhoneCode(code: '+1-876	', name: '	Jamaica'),
  const PhoneCode(code: '+81	', name: '	Japan'),
  const PhoneCode(code: '+44-1534	', name: '	Jersey'),
  const PhoneCode(code: '+962	', name: '	Jordan'),
  const PhoneCode(code: '+7	', name: '	Kazakhstan'),
  const PhoneCode(code: '+254	', name: '	Kenya'),
  const PhoneCode(code: '+686	', name: '	Kiribati'),
  const PhoneCode(code: '+383	', name: '	Kosovo'),
  const PhoneCode(code: '+965	', name: '	Kuwait'),
  const PhoneCode(code: '+996	', name: '	Kyrgyzstan'),
  const PhoneCode(code: '+856	', name: '	Laos'),
  const PhoneCode(code: '+371	', name: '	Latvia'),
  const PhoneCode(code: '+961	', name: '	Lebanon'),
  const PhoneCode(code: '+266	', name: '	Lesotho'),
  const PhoneCode(code: '+231	', name: '	Liberia'),
  const PhoneCode(code: '+218	', name: '	Libya'),
  const PhoneCode(code: '+423	', name: '	Liechtenstein'),
  const PhoneCode(code: '+370	', name: '	Lithuania'),
  const PhoneCode(code: '+352	', name: '	Luxembourg'),
  const PhoneCode(code: '+853	', name: '	Macau'),
  const PhoneCode(code: '+389	', name: '	Macedonia'),
  const PhoneCode(code: '+261	', name: '	Madagascar'),
  const PhoneCode(code: '+265	', name: '	Malawi'),
  const PhoneCode(code: '+60	', name: '	Malaysia'),
  const PhoneCode(code: '+960	', name: '	Maldives'),
  const PhoneCode(code: '+223	', name: '	Mali'),
  const PhoneCode(code: '+356	', name: '	Malta'),
  const PhoneCode(code: '+692	', name: '	Marshall Islands'),
  const PhoneCode(code: '+222	', name: '	Mauritania'),
  const PhoneCode(code: '+230	', name: '	Mauritius'),
  const PhoneCode(code: '+262	', name: '	Mayotte'),
  const PhoneCode(code: '+52	', name: '	Mexico'),
  const PhoneCode(code: '+691	', name: '	Micronesia'),
  const PhoneCode(code: '+373	', name: '	Moldova'),
  const PhoneCode(code: '+377	', name: '	Monaco'),
  const PhoneCode(code: '+976	', name: '	Mongolia'),
  const PhoneCode(code: '+382	', name: '	Montenegro'),
  const PhoneCode(code: '+1-664	', name: '	Montserrat'),
  const PhoneCode(code: '+212	', name: '	Morocco'),
  const PhoneCode(code: '+258	', name: '	Mozambique'),
  const PhoneCode(code: '+95	', name: '	Myanmar'),
  const PhoneCode(code: '+264	', name: '	Namibia'),
  const PhoneCode(code: '+674	', name: '	Nauru'),
  const PhoneCode(code: '+977	', name: '	Nepal'),
  const PhoneCode(code: '+31	', name: '	Netherlands'),
  const PhoneCode(code: '+599	', name: '	Netherlands Antilles'),
  const PhoneCode(code: '+687	', name: '	New Caledonia'),
  const PhoneCode(code: '+64	', name: '	New Zealand'),
  const PhoneCode(code: '+505	', name: '	Nicaragua'),
  const PhoneCode(code: '+227	', name: '	Niger'),
  const PhoneCode(code: '+234	', name: '	Nigeria'),
  const PhoneCode(code: '+683	', name: '	Niue'),
  const PhoneCode(code: '+850	', name: '	North Korea'),
  const PhoneCode(code: '+1-670	', name: '	Northern Mariana Islands'),
  const PhoneCode(code: '+47	', name: '	Norway'),
  const PhoneCode(code: '+968	', name: '	Oman'),
  const PhoneCode(code: '+92	', name: '	Pakistan'),
  const PhoneCode(code: '+680	', name: '	Palau'),
  const PhoneCode(code: '+970	', name: '	Palestine'),
  const PhoneCode(code: '+507	', name: '	Panama'),
  const PhoneCode(code: '+675	', name: '	Papua New Guinea'),
  const PhoneCode(code: '+595	', name: '	Paraguay'),
  const PhoneCode(code: '+51	', name: '	Peru'),
  const PhoneCode(code: '+63	', name: '	Philippines'),
  const PhoneCode(code: '+64	', name: '	Pitcairn'),
  const PhoneCode(code: '+48	', name: '	Poland'),
  const PhoneCode(code: '+351	', name: '	Portugal'),
  const PhoneCode(code: '+1-787', name: '	Puerto Rico'),
  const PhoneCode(code: '+974	', name: '	Qatar'),
  const PhoneCode(code: '+242	', name: '	Republic of the Congo'),
  const PhoneCode(code: '+262	', name: '	Reunion'),
  const PhoneCode(code: '+40	', name: '	Romania'),
  const PhoneCode(code: '+7	', name: '	Russia'),
  const PhoneCode(code: '+250	', name: '	Rwanda'),
  const PhoneCode(code: '+590	', name: '	Saint Barthelemy'),
  const PhoneCode(code: '+290	', name: '	Saint Helena'),
  const PhoneCode(code: '+1-869	', name: '	Saint Kitts and Nevis'),
  const PhoneCode(code: '+1-758	', name: '	Saint Lucia'),
  const PhoneCode(code: '+590	', name: '	Saint Martin'),
  const PhoneCode(code: '+508	', name: '	Saint Pierre and Miquelon'),
  const PhoneCode(code: '+1-784	', name: '	Saint Vincent and the Grenadines'),
  const PhoneCode(code: '+685	', name: '	Samoa'),
  const PhoneCode(code: '+378	', name: '	San Marino'),
  const PhoneCode(code: '+239	', name: '	Sao Tome and Principe'),
  const PhoneCode(code: '+966	', name: '	Saudi Arabia'),
  const PhoneCode(code: '+221	', name: '	Senegal'),
  const PhoneCode(code: '+381	', name: '	Serbia'),
  const PhoneCode(code: '+248	', name: '	Seychelles'),
  const PhoneCode(code: '+232	', name: '	Sierra Leone'),
  const PhoneCode(code: '+65	', name: '	Singapore'),
  const PhoneCode(code: '+1-721	', name: '	Sint Maarten'),
  const PhoneCode(code: '+421	', name: '	Slovakia'),
  const PhoneCode(code: '+386	', name: '	Slovenia'),
  const PhoneCode(code: '+677	', name: '	Solomon Islands'),
  const PhoneCode(code: '+252	', name: '	Somalia'),
  const PhoneCode(code: '+27	', name: '	South Africa'),
  const PhoneCode(code: '+82	', name: '	South Korea'),
  const PhoneCode(code: '+211	', name: '	South Sudan'),
  const PhoneCode(code: '+34	', name: '	Spain'),
  const PhoneCode(code: '+94	', name: '	Sri Lanka'),
  const PhoneCode(code: '+249	', name: '	Sudan'),
  const PhoneCode(code: '+597	', name: '	Suriname'),
  const PhoneCode(code: '+47	', name: '	Svalbard and Jan Mayen'),
  const PhoneCode(code: '+268	', name: '	Swaziland'),
  const PhoneCode(code: '+46	', name: '	Sweden'),
  const PhoneCode(code: '+41	', name: '	Switzerland'),
  const PhoneCode(code: '+963	', name: '	Syria'),
  const PhoneCode(code: '+886	', name: '	Taiwan'),
  const PhoneCode(code: '+992	', name: '	Tajikistan'),
  const PhoneCode(code: '+255	', name: '	Tanzania'),
  const PhoneCode(code: '+66	', name: '	Thailand'),
  const PhoneCode(code: '+228	', name: '	Togo'),
  const PhoneCode(code: '+690	', name: '	Tokelau'),
  const PhoneCode(code: '+676	', name: '	Tonga'),
  const PhoneCode(code: '+1-868	', name: '	Trinidad and Tobago'),
  const PhoneCode(code: '+216	', name: '	Tunisia'),
  const PhoneCode(code: '+90	', name: '	Turkey'),
  const PhoneCode(code: '+993	', name: '	Turkmenistan'),
  const PhoneCode(code: '+1-649	', name: '	Turks and Caicos Islands'),
  const PhoneCode(code: '+688	', name: '	Tuvalu'),
  const PhoneCode(code: '+1-340	', name: '	U.S. Virgin Islands'),
  const PhoneCode(code: '+256	', name: '	Uganda'),
  const PhoneCode(code: '+380	', name: '	Ukraine'),
  const PhoneCode(code: '+971	', name: '	United Arab Emirates'),
  const PhoneCode(code: '+44	', name: '	United Kingdom'),
  const PhoneCode(code: '+1	', name: '	United States'),
  const PhoneCode(code: '+598	', name: '	Uruguay'),
  const PhoneCode(code: '+998	', name: '	Uzbekistan'),
  const PhoneCode(code: '+678	', name: '	Vanuatu'),
  const PhoneCode(code: '+379	', name: '	Vatican'),
  const PhoneCode(code: '+58	', name: '	Venezuela'),
  const PhoneCode(code: '+84	', name: '	Vietnam'),
  const PhoneCode(code: '+681	', name: '	Wallis and Futuna'),
  const PhoneCode(code: '+212	', name: '	Western Sahara'),
  const PhoneCode(code: '+967	', name: '	Yemen'),
  const PhoneCode(code: '+260	', name: '	Zambia'),
  const PhoneCode(code: '+263	', name: '	Zimbabwe'),
];
PhoneCode selectedphonecode;

class CountryCode {
  const CountryCode({this.code, this.name});
  final String code;
  final String name;
}

List<CountryCode> country = <CountryCode>[
  const CountryCode(code: '+93	', name: '	Afghanistan'),
  const CountryCode(code: '+355	', name: '	Albania'),
  const CountryCode(code: '+213	', name: '	Algeria'),
  const CountryCode(code: '+1-684	', name: '	American Samoa'),
  const CountryCode(code: '+376	', name: '	Andorra'),
  const CountryCode(code: '+244	', name: '	Angola'),
  const CountryCode(code: '+1-264	', name: '	Anguilla'),
  const CountryCode(code: '+672	', name: '	Antarctica'),
  const CountryCode(code: '+1-268	', name: '	Antigua '),
  const CountryCode(code: '+54	', name: '	Argentina'),
  const CountryCode(code: '+374	', name: '	Armenia'),
  const CountryCode(code: '+297	', name: '	Aruba'),
  const CountryCode(code: '+61	', name: '	Australia'),
  const CountryCode(code: '+43	', name: '	Austria'),
  const CountryCode(code: '+994	', name: '	Azerbaijan'),
  const CountryCode(code: '+1-242	', name: '	Bahamas'),
  const CountryCode(code: '+973	', name: '	Bahrain'),
  const CountryCode(code: '+880	', name: '	Bangladesh'),
  const CountryCode(code: '+1-246	', name: '	Barbados'),
  const CountryCode(code: '+375	', name: '	Belarus'),
  const CountryCode(code: '+32	', name: '	Belgium'),
  const CountryCode(code: '+501	', name: '	Belize'),
  const CountryCode(code: '+229	', name: '	Benin'),
  const CountryCode(code: '+1-441	', name: '	Bermuda'),
  const CountryCode(code: '+975	', name: '	Bhutan'),
  const CountryCode(code: '+591	', name: '	Bolivia'),
  const CountryCode(code: '+387	', name: '	Bosnia and Herzegovina'),
  const CountryCode(code: '+267	', name: '	Botswana'),
  const CountryCode(code: '+55	', name: '	Brazil'),
  const CountryCode(code: '+246	', name: '	British Indian Ocean Territory'),
  const CountryCode(code: '+1-284	', name: '	British Virgin Islands'),
  const CountryCode(code: '+673	', name: '	Brunei'),
  const CountryCode(code: '+359	', name: '	Bulgaria'),
  const CountryCode(code: '+226	', name: '	Burkina Faso'),
  const CountryCode(code: '+257	', name: '	Burundi'),
  const CountryCode(code: '+855	', name: '	Cambodia'),
  const CountryCode(code: '+237	', name: '	Cameroon'),
  const CountryCode(code: '+1	', name: '	Canada'),
  const CountryCode(code: '+238	', name: '	Cape Verde'),
  const CountryCode(code: '+1-345	', name: '	Cayman Islands'),
  const CountryCode(code: '+236	', name: '	Central African Republic'),
  const CountryCode(code: '+235	', name: '	Chad'),
  const CountryCode(code: '+56	', name: '	Chile'),
  const CountryCode(code: '+86	', name: '	China'),
  const CountryCode(code: '+61	', name: '	Christmas Island'),
  const CountryCode(code: '+61	', name: '	Cocos Islands'),
  const CountryCode(code: '+57	', name: '	Colombia'),
  const CountryCode(code: '+269	', name: '	Comoros'),
  const CountryCode(code: '+682	', name: '	Cook Islands'),
  const CountryCode(code: '+506	', name: '	Costa Rica'),
  const CountryCode(code: '+385	', name: '	Croatia'),
  const CountryCode(code: '+53	', name: '	Cuba'),
  const CountryCode(code: '+599	', name: '	Curacao'),
  const CountryCode(code: '+357	', name: '	Cyprus'),
  const CountryCode(code: '+420	', name: '	Czech Republic'),
  const CountryCode(code: '+243	', name: '	Democratic Republic of the Congo'),
  const CountryCode(code: '+45	', name: '	Denmark'),
  const CountryCode(code: '+253	', name: '	Djibouti'),
  const CountryCode(code: '+1-767	', name: '	Dominica'),
  const CountryCode(code: '+1-809', name: '	Dominican Republic'),
  const CountryCode(code: '+670	', name: '	East Timor'),
  const CountryCode(code: '+593	', name: '	Ecuador'),
  const CountryCode(code: '+20	', name: '	Egypt'),
  const CountryCode(code: '+503	', name: '	El Salvador'),
  const CountryCode(code: '+240	', name: '	Equatorial Guinea'),
  const CountryCode(code: '+291	', name: '	Eritrea'),
  const CountryCode(code: '+372	', name: '	Estonia'),
  const CountryCode(code: '+251	', name: '	Ethiopia'),
  const CountryCode(code: '+500	', name: '	Falkland Islands'),
  const CountryCode(code: '+298	', name: '	Faroe Islands'),
  const CountryCode(code: '+679	', name: '	Fiji'),
  const CountryCode(code: '+358	', name: '	Finland'),
  const CountryCode(code: '+33	', name: '	France'),
  const CountryCode(code: '+689	', name: '	French Polynesia'),
  const CountryCode(code: '+241	', name: '	Gabon'),
  const CountryCode(code: '+220	', name: '	Gambia'),
  const CountryCode(code: '+995	', name: '	Georgia'),
  const CountryCode(code: '+49	', name: '	Germany'),
  const CountryCode(code: '+233	', name: '	Ghana'),
  const CountryCode(code: '+350	', name: '	Gibraltar'),
  const CountryCode(code: '+30	', name: '	Greece'),
  const CountryCode(code: '+299	', name: '	Greenland'),
  const CountryCode(code: '+1-473	', name: '	Grenada'),
  const CountryCode(code: '+1-671	', name: '	Guam'),
  const CountryCode(code: '+502	', name: '	Guatemala'),
  const CountryCode(code: '+44-1481	', name: '	Guernsey'),
  const CountryCode(code: '+224	', name: '	Guinea'),
  const CountryCode(code: '+245	', name: '	Guinea-Bissau'),
  const CountryCode(code: '+592	', name: '	Guyana'),
  const CountryCode(code: '+509	', name: '	Haiti'),
  const CountryCode(code: '+504	', name: '	Honduras'),
  const CountryCode(code: '+852	', name: '	Hong Kong'),
  const CountryCode(code: '+36	', name: '	Hungary'),
  const CountryCode(code: '+354	', name: '	Iceland'),
  const CountryCode(code: '+91	', name: '	India'),
  const CountryCode(code: '+62	', name: '	Indonesia'),
  const CountryCode(code: '+98	', name: '	Iran'),
  const CountryCode(code: '+964	', name: '	Iraq'),
  const CountryCode(code: '+353	', name: '	Ireland'),
  const CountryCode(code: '+44-1624	', name: '	Isle of Man'),
  const CountryCode(code: '+972	', name: '	Israel'),
  const CountryCode(code: '+39	', name: '	Italy'),
  const CountryCode(code: '+225	', name: '	Ivory Coast'),
  const CountryCode(code: '+1-876	', name: '	Jamaica'),
  const CountryCode(code: '+81	', name: '	Japan'),
  const CountryCode(code: '+44-1534	', name: '	Jersey'),
  const CountryCode(code: '+962	', name: '	Jordan'),
  const CountryCode(code: '+7	', name: '	Kazakhstan'),
  const CountryCode(code: '+254	', name: '	Kenya'),
  const CountryCode(code: '+686	', name: '	Kiribati'),
  const CountryCode(code: '+383	', name: '	Kosovo'),
  const CountryCode(code: '+965	', name: '	Kuwait'),
  const CountryCode(code: '+996	', name: '	Kyrgyzstan'),
  const CountryCode(code: '+856	', name: '	Laos'),
  const CountryCode(code: '+371	', name: '	Latvia'),
  const CountryCode(code: '+961	', name: '	Lebanon'),
  const CountryCode(code: '+266	', name: '	Lesotho'),
  const CountryCode(code: '+231	', name: '	Liberia'),
  const CountryCode(code: '+218	', name: '	Libya'),
  const CountryCode(code: '+423	', name: '	Liechtenstein'),
  const CountryCode(code: '+370	', name: '	Lithuania'),
  const CountryCode(code: '+352	', name: '	Luxembourg'),
  const CountryCode(code: '+853	', name: '	Macau'),
  const CountryCode(code: '+389	', name: '	Macedonia'),
  const CountryCode(code: '+261	', name: '	Madagascar'),
  const CountryCode(code: '+265	', name: '	Malawi'),
  const CountryCode(code: '+60	', name: '	Malaysia'),
  const CountryCode(code: '+960	', name: '	Maldives'),
  const CountryCode(code: '+223	', name: '	Mali'),
  const CountryCode(code: '+356	', name: '	Malta'),
  const CountryCode(code: '+692	', name: '	Marshall Islands'),
  const CountryCode(code: '+222	', name: '	Mauritania'),
  const CountryCode(code: '+230	', name: '	Mauritius'),
  const CountryCode(code: '+262	', name: '	Mayotte'),
  const CountryCode(code: '+52	', name: '	Mexico'),
  const CountryCode(code: '+691	', name: '	Micronesia'),
  const CountryCode(code: '+373	', name: '	Moldova'),
  const CountryCode(code: '+377	', name: '	Monaco'),
  const CountryCode(code: '+976	', name: '	Mongolia'),
  const CountryCode(code: '+382	', name: '	Montenegro'),
  const CountryCode(code: '+1-664	', name: '	Montserrat'),
  const CountryCode(code: '+212	', name: '	Morocco'),
  const CountryCode(code: '+258	', name: '	Mozambique'),
  const CountryCode(code: '+95	', name: '	Myanmar'),
  const CountryCode(code: '+264	', name: '	Namibia'),
  const CountryCode(code: '+674	', name: '	Nauru'),
  const CountryCode(code: '+977	', name: '	Nepal'),
  const CountryCode(code: '+31	', name: '	Netherlands'),
  const CountryCode(code: '+599	', name: '	Netherlands Antilles'),
  const CountryCode(code: '+687	', name: '	New Caledonia'),
  const CountryCode(code: '+64	', name: '	New Zealand'),
  const CountryCode(code: '+505	', name: '	Nicaragua'),
  const CountryCode(code: '+227	', name: '	Niger'),
  const CountryCode(code: '+234	', name: '	Nigeria'),
  const CountryCode(code: '+683	', name: '	Niue'),
  const CountryCode(code: '+850	', name: '	North Korea'),
  const CountryCode(code: '+1-670	', name: '	Northern Mariana Islands'),
  const CountryCode(code: '+47	', name: '	Norway'),
  const CountryCode(code: '+968	', name: '	Oman'),
  const CountryCode(code: '+92	', name: '	Pakistan'),
  const CountryCode(code: '+680	', name: '	Palau'),
  const CountryCode(code: '+970	', name: '	Palestine'),
  const CountryCode(code: '+507	', name: '	Panama'),
  const CountryCode(code: '+675	', name: '	Papua New Guinea'),
  const CountryCode(code: '+595	', name: '	Paraguay'),
  const CountryCode(code: '+51	', name: '	Peru'),
  const CountryCode(code: '+63	', name: '	Philippines'),
  const CountryCode(code: '+64	', name: '	Pitcairn'),
  const CountryCode(code: '+48	', name: '	Poland'),
  const CountryCode(code: '+351	', name: '	Portugal'),
  const CountryCode(code: '+1-787', name: '	Puerto Rico'),
  const CountryCode(code: '+974	', name: '	Qatar'),
  const CountryCode(code: '+242	', name: '	Republic of the Congo'),
  const CountryCode(code: '+262	', name: '	Reunion'),
  const CountryCode(code: '+40	', name: '	Romania'),
  const CountryCode(code: '+7	', name: '	Russia'),
  const CountryCode(code: '+250	', name: '	Rwanda'),
  const CountryCode(code: '+590	', name: '	Saint Barthelemy'),
  const CountryCode(code: '+290	', name: '	Saint Helena'),
  const CountryCode(code: '+1-869	', name: '	Saint Kitts and Nevis'),
  const CountryCode(code: '+1-758	', name: '	Saint Lucia'),
  const CountryCode(code: '+590	', name: '	Saint Martin'),
  const CountryCode(code: '+508	', name: '	Saint Pierre and Miquelon'),
  const CountryCode(code: '+1-784	', name: '	Saint Vincent and the Grenadines'),
  const CountryCode(code: '+685	', name: '	Samoa'),
  const CountryCode(code: '+378	', name: '	San Marino'),
  const CountryCode(code: '+239	', name: '	Sao Tome and Principe'),
  const CountryCode(code: '+966	', name: '	Saudi Arabia'),
  const CountryCode(code: '+221	', name: '	Senegal'),
  const CountryCode(code: '+381	', name: '	Serbia'),
  const CountryCode(code: '+248	', name: '	Seychelles'),
  const CountryCode(code: '+232	', name: '	Sierra Leone'),
  const CountryCode(code: '+65	', name: '	Singapore'),
  const CountryCode(code: '+1-721	', name: '	Sint Maarten'),
  const CountryCode(code: '+421	', name: '	Slovakia'),
  const CountryCode(code: '+386	', name: '	Slovenia'),
  const CountryCode(code: '+677	', name: '	Solomon Islands'),
  const CountryCode(code: '+252	', name: '	Somalia'),
  const CountryCode(code: '+27	', name: '	South Africa'),
  const CountryCode(code: '+82	', name: '	South Korea'),
  const CountryCode(code: '+211	', name: '	South Sudan'),
  const CountryCode(code: '+34	', name: '	Spain'),
  const CountryCode(code: '+94	', name: '	Sri Lanka'),
  const CountryCode(code: '+249	', name: '	Sudan'),
  const CountryCode(code: '+597	', name: '	Suriname'),
  const CountryCode(code: '+47	', name: '	Svalbard and Jan Mayen'),
  const CountryCode(code: '+268	', name: '	Swaziland'),
  const CountryCode(code: '+46	', name: '	Sweden'),
  const CountryCode(code: '+41	', name: '	Switzerland'),
  const CountryCode(code: '+963	', name: '	Syria'),
  const CountryCode(code: '+886	', name: '	Taiwan'),
  const CountryCode(code: '+992	', name: '	Tajikistan'),
  const CountryCode(code: '+255	', name: '	Tanzania'),
  const CountryCode(code: '+66	', name: '	Thailand'),
  const CountryCode(code: '+228	', name: '	Togo'),
  const CountryCode(code: '+690	', name: '	Tokelau'),
  const CountryCode(code: '+676	', name: '	Tonga'),
  const CountryCode(code: '+1-868	', name: '	Trinidad and Tobago'),
  const CountryCode(code: '+216	', name: '	Tunisia'),
  const CountryCode(code: '+90	', name: '	Turkey'),
  const CountryCode(code: '+993	', name: '	Turkmenistan'),
  const CountryCode(code: '+1-649	', name: '	Turks and Caicos Islands'),
  const CountryCode(code: '+688	', name: '	Tuvalu'),
  const CountryCode(code: '+1-340	', name: '	U.S. Virgin Islands'),
  const CountryCode(code: '+256	', name: '	Uganda'),
  const CountryCode(code: '+380	', name: '	Ukraine'),
  const CountryCode(code: '+971	', name: '	United Arab Emirates'),
  const CountryCode(code: '+44	', name: '	United Kingdom'),
  const CountryCode(code: '+1	', name: '	United States'),
  const CountryCode(code: '+598	', name: '	Uruguay'),
  const CountryCode(code: '+998	', name: '	Uzbekistan'),
  const CountryCode(code: '+678	', name: '	Vanuatu'),
  const CountryCode(code: '+379	', name: '	Vatican'),
  const CountryCode(code: '+58	', name: '	Venezuela'),
  const CountryCode(code: '+84	', name: '	Vietnam'),
  const CountryCode(code: '+681	', name: '	Wallis and Futuna'),
  const CountryCode(code: '+212	', name: '	Western Sahara'),
  const CountryCode(code: '+967	', name: '	Yemen'),
  const CountryCode(code: '+260	', name: '	Zambia'),
  const CountryCode(code: '+263	', name: '	Zimbabwe'),
];
CountryCode selectedCountry;

//location
class PaymentMethod {
  const PaymentMethod({this.payname});

  final String payname;
}

List<PaymentMethod> paymentmethod = <PaymentMethod>[
  const PaymentMethod(
    payname: 'National bank transfer',
  ),
  const PaymentMethod(
    payname: 'SEPA (EU) bank transfer',
  ),
  const PaymentMethod(
    payname: 'Transfers with specific bank',
  ),
  const PaymentMethod(
    payname: 'International Wire (SWIFT)',
  ),
  const PaymentMethod(
    payname: 'Other online payment',
  ),
  const PaymentMethod(
    payname: 'Cash deposit',
  ),
  const PaymentMethod(
    payname: 'EcoCash',
  ),
  const PaymentMethod(
    payname: 'Hal-cash',
  ),
  const PaymentMethod(
    payname: 'Swish',
  ),
  const PaymentMethod(
    payname: 'Vipps',
  ),
  const PaymentMethod(
    payname: 'MobilePay FI',
  ),
  const PaymentMethod(
    payname: 'QIWI',
  ),
  const PaymentMethod(
    payname: 'TELE2',
  ),
  const PaymentMethod(
    payname: 'IMPS Bank Transfer India',
  ),
  const PaymentMethod(
    payname: 'PayTM',
  ),
  const PaymentMethod(
    payname: 'Lydia',
  ),
  const PaymentMethod(
    payname: 'Interac e-transfer',
  ),
  const PaymentMethod(
    payname: 'Pingit',
  ),
  const PaymentMethod(
    payname: 'Paym',
  ),
  const PaymentMethod(
    payname: 'PYC',
  ),
  const PaymentMethod(
    payname: 'Alipay',
  ),
  const PaymentMethod(
    payname: 'Superflash',
  ),
  const PaymentMethod(
    payname: 'Chase Quickpay',
  ),
  const PaymentMethod(
    payname: 'OKPay',
  ),
  const PaymentMethod(
    payname: 'Paypal',
  ),
  const PaymentMethod(
    payname: 'WebMoney',
  ),
  const PaymentMethod(
    payname: 'Moneybookers / Skrill',
  ),
  const PaymentMethod(
    payname: 'Neteller',
  ),
  const PaymentMethod(
    payname: 'Western Union',
  ),
  const PaymentMethod(
    payname: 'PostePay',
  ),
  const PaymentMethod(
    payname: 'Moneygram',
  ),
  const PaymentMethod(
    payname: 'Cashier\'s check',
  ),
  const PaymentMethod(
    payname: 'Venmo',
  ),
  const PaymentMethod(
    payname: 'Zelle',
  ),
  const PaymentMethod(
    payname: 'Dwolla',
  ),
  const PaymentMethod(
    payname: 'Perfect Money',
  ),
  const PaymentMethod(
    payname: 'CashU',
  ),
  const PaymentMethod(
    payname: 'Payza',
  ),
  const PaymentMethod(
    payname: 'AstroPay',
  ),
  const PaymentMethod(
    payname: 'M-PESA Kenya (Safaricom)',
  ),
  const PaymentMethod(
    payname: 'M-PESA Tanzania (Vodacom)',
  ),
  const PaymentMethod(
    payname: 'Other Online Wallet',
  ),
  const PaymentMethod(
    payname: 'Other Online Wallet (Global)',
  ),
  const PaymentMethod(
    payname: 'Other Remittance',
  ),
  const PaymentMethod(
    payname: 'Bitmain Coupon',
  ),
  const PaymentMethod(
    payname: 'Google Wallet',
  ),
  const PaymentMethod(
    payname: 'Vanilla',
  ),
  const PaymentMethod(
    payname: 'Transferwise',
  ),
  const PaymentMethod(
    payname: 'PayPal My Cash',
  ),
  const PaymentMethod(
    payname: 'RIA Money Transfer',
  ),
  const PaymentMethod(
    payname: 'SolidTrustPay',
  ),
  const PaymentMethod(
    payname: 'Xoom',
  ),
  const PaymentMethod(
    payname: 'MobilePay',
  ),
  const PaymentMethod(
    payname: 'Telegramatic Order',
  ),
  const PaymentMethod(
    payname: 'Payeer',
  ),
  const PaymentMethod(
    payname: 'advcash',
  ),
  const PaymentMethod(
    payname: 'hyperWALLET',
  ),
  const PaymentMethod(
    payname: 'MobilePay NO',
  ),
  const PaymentMethod(
    payname: 'Tigo-Pesa Tanzania',
  ),
  const PaymentMethod(
    payname: 'Ripple altcoin',
  ),
  const PaymentMethod(
    payname: 'Payoneer',
  ),
  const PaymentMethod(
    payname: 'Square Cash',
  ),
  const PaymentMethod(
    payname: 'Paxum',
  ),
  const PaymentMethod(
    payname: 'Cash at ATM',
  ),
  const PaymentMethod(
    payname: 'Litecoin altcoin',
  ),
  const PaymentMethod(
    payname: 'Credit card',
  ),
  const PaymentMethod(
    payname: 'WeChat',
  ),
  const PaymentMethod(
    payname: 'Reloadit',
  ),
  const PaymentMethod(
    payname: 'Walmart 2 Walmart',
  ),
  const PaymentMethod(
    payname: 'Easypaisa',
  ),
  const PaymentMethod(
    payname: 'Serve2Serve',
  ),
  const PaymentMethod(
    payname: 'Worldremit',
  ),
  const PaymentMethod(
    payname: 'Ethereum altcoin',
  ),
  const PaymentMethod(
    payname: 'Yandex Money',
  ),
];
PaymentMethod selectedpayname;

//Currency
class Currency {
  const Currency({this.currency});

  final String currency;
}

List<Currency> currency = <Currency>[
  const Currency(
    currency: 'INR',
  ),
  const Currency(
    currency: 'USD',
  ),
  const Currency(
    currency: 'AED',
  ),
  const Currency(
    currency: 'AUD',
  ),
  const Currency(
    currency: 'EUR',
  ),
  const Currency(
    currency: 'JPY',
  ),
  const Currency(
    currency: 'CNY',
  ),
  const Currency(
    currency: 'GBP',
  ),
  const Currency(
    currency: 'CAD',
  ),
  const Currency(
    currency: 'CHF',
  ),
  const Currency(
    currency: 'KRW',
  ),
];
Currency selectedcurrecny;

//hour
class Hour {
  const Hour({this.hourtime});

  final String hourtime;
}

List<Hour> hourtime = <Hour>[
  const Hour(hourtime: '00:00'),
  const Hour(hourtime: '00:30'),
  const Hour(hourtime: '01:00'),
  const Hour(hourtime: '01:30'),
  const Hour(hourtime: '02:00'),
  const Hour(hourtime: '02:30'),
  const Hour(hourtime: '03:00'),
  const Hour(hourtime: '03:30'),
  const Hour(hourtime: '04:00'),
  const Hour(hourtime: '04:30'),
  const Hour(hourtime: '05:00'),
  const Hour(hourtime: '05:30'),
  const Hour(hourtime: '06:00'),
  const Hour(hourtime: '06:30'),
  const Hour(hourtime: '07:00'),
  const Hour(hourtime: '07:30'),
  const Hour(hourtime: '08:00'),
  const Hour(hourtime: '08:30'),
  const Hour(hourtime: '09:00'),
  const Hour(hourtime: '09:30'),
  const Hour(hourtime: '10:00'),
  const Hour(hourtime: '10:30'),
  const Hour(hourtime: '11:00'),
  const Hour(hourtime: '11:30'),
  const Hour(hourtime: '12:00'),
  const Hour(hourtime: '12:30'),
  const Hour(hourtime: '13:00'),
  const Hour(hourtime: '13:30'),
  const Hour(hourtime: '14:00'),
  const Hour(hourtime: '14:30'),
  const Hour(hourtime: '15:00'),
  const Hour(hourtime: '15:30'),
  const Hour(hourtime: '16:00'),
  const Hour(hourtime: '16:30'),
  const Hour(hourtime: '17:00'),
  const Hour(hourtime: '17:30'),
  const Hour(hourtime: '18:00'),
  const Hour(hourtime: '18:30'),
  const Hour(hourtime: '19:00'),
  const Hour(hourtime: '19:30'),
  const Hour(hourtime: '20:00'),
  const Hour(hourtime: '20:30'),
  const Hour(hourtime: '21:00'),
  const Hour(hourtime: '21:30'),
  const Hour(hourtime: '22:00'),
  const Hour(hourtime: '22:30'),
  const Hour(hourtime: '23:00'),
  const Hour(hourtime: '23:30'),
];
Hour suns;
Hour sune;

Hour mons;
Hour mone;

Hour tues;
Hour tuee;

Hour weds;
Hour wede;

Hour thus;
Hour thue;

Hour fris;
Hour frie;

Hour sats;
Hour sate;

//Estimated trade

class EstimatedTrade {
  const EstimatedTrade({this.limit1, this.limit2});
  final String limit1;
  final String limit2;
}

List<EstimatedTrade> estimatedTradeList = <EstimatedTrade>[
  const EstimatedTrade(limit1: '0', limit2: '1000'),
  const EstimatedTrade(limit1: '1000', limit2: '20000'),
  const EstimatedTrade(limit1: '20000', limit2: '200000'),
  const EstimatedTrade(limit1: '200000', limit2: '1000000'),
  const EstimatedTrade(limit1: '10000001', limit2: '1000000000'),
];
EstimatedTrade selectedEstimatedTrade;
